name: CI

on: [ push ]

jobs:
  test:
    strategy: 
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: ubuntu-latest, crystal: 0.36.1}
    runs-on: ${{matrix.os}}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - uses: actions/checkout@v2
      - run: crystal spec
      - run: crystal tool format --check